This is makeindex, version 2.15 [MiKTeX 2.9] (kpathsea + Thai support).
Scanning style file D:/Vikman/Dropbox/Universidad/Organo/Memoria/pfc_amroldan.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file pfc_amroldan.acn....done (69 entries accepted, 0 rejected).
Sorting entries....done (431 comparisons).
Generating output file pfc_amroldan.acr....done (44 lines written, 0 warnings).
Output written in pfc_amroldan.acr.
Transcript written in pfc_amroldan.alg.
