#!/bin/sh
# Daemon script
# Victor Manuel Fernandez Castro
# 2 August 2015

### BEGIN INIT INFO
# Provides:          organ
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start organ daemon at boot time
# Description:       Provides a socket for playing MIDI on GPIO.
### END INIT INFO

SOCKET="/run/organd.sock"
SBIN='/usr/local/sbin'
DAEMON='organd'
USER="organ"
GROUP="organ"

. /lib/lsb/init-functions

start() {
	log_daemon_msg "Iniciando controlador del organo"
	pid=$(ps -e | grep $DAEMON | cut -b-5)

	if [ ! -z "$pid" ]; then
		log_warning_msg "Servicio ya iniciado"
	else
		$SBIN/$DAEMON $(id -u $USER) $(id -g $GROUP)

		if [ $? != "0" ]; then
			log_end_msg 1
			exit 1
		else
			log_end_msg 0
		fi
	fi
}

stop() {
	log_daemon_msg "Deteniendo controlador del organo"
	pid=$(ps -e | grep $DAEMON | cut -b-5)

	if [ -z "$pid" ]; then
		log_warning_msg "El servicio no estaba iniciado"
	else
		kill $pid

		if [ $? != 0 ]; then
			log_end_msg 1
			exit 1
		else
			until [ -z $(ps -e | grep $DAEMON | cut -b-5) ]; do
				sleep 1
			done
			
			rm -f $SOCKET
			log_end_msg 0
		fi
	fi
}

case $1 in
	"start")
		start
		;;

	"stop")
		stop
		;;
	
	"restart")
		stop
		start
		;;
	
	"force-reload")
		;;
	
	"status")
		if [ -z $(ps -e | grep $DAEMON | cut -b-5) ]; then
			log_action_msg "Servicio no iniciado"
		else
			log_action_msg "Servicio iniciado"
			organ status
		fi	
		;;
	
		

	*)
		echo "Sintaxis:" $0 "start|stop|restart|force-reload|status|"
		exit 1
esac
