#!/bin/sh
# Daemon script
# Victor Manuel Fernandez Castro
# 2 August 2015

### BEGIN INIT INFO
# Provides:          organ
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start organ daemon at boot time
# Description:       Provides a socket for playing MIDI on GPIO.
### END INIT INFO

SOCKET="/run/organd.sock"
DAEMON='organd'
USER="organ"
GROUP="organ"

. /lib/lsb/init-functions

case $1 in
	"start")
		log_daemon_msg "Iniciando controlador del organo..."
		pid=$(ps -e | grep $DAEMON | cut -b-5)

		if [ ! -z "$pid" ]; then
			log_progress_msg "Servicio ya iniciado"
			log_end_msg 0
		else
			/usr/sbin/$DAEMON $(id -u $USER) $(id -g $GROUP)

			if [ $? != "0" ]; then
				log_failure_msg "No se pudo iniciar el servicio"
				exit 1
			else
				log_end_msg 0
			fi
		fi
		;;

	"stop")
		log_daemon_msg "Deteniendo controlador del organo..."
		pid=$(ps -e | grep $DAEMON | cut -b-5)

		if [ -z "$pid" ]; then
			log_progress_msg "El servicio no estaba iniciado"
			log_end_msg 0
		else
			kill $pid

			if [ $? != 0 ]; then
				log_failure_msg "No se pudo parar el servicio"
				exit 1
			else
				until [ -z $(ps -e | grep $DAEMON | cut -b-5) ]; do
					sleep 1
				done
				rm -f $SOCKET
				log_end_msg 0
			fi
		fi
		;;

	*)
		echo "Sintaxis:" $0 "start|stop"
		exit 1
esac
