#!/bin/sh
# Remote daemon script
# Victor Manuel Fernandez Castro
# 14 August 2015

### BEGIN INIT INFO
# Provides:          remote
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start remote daemon at boot time
# Description:       Provides a socket for listen a remote control.
### END INIT INFO

DAEMON='remoted'
USER="organ"
GROUP="organ"

. /lib/lsb/init-functions

case $1 in
	"start")
		log_daemon_msg "Iniciando servicio..."
		pid=$(ps -e | grep $DAEMON | cut -d' ' -f2)

		if [ ! -z "$pid" ]; then
			log_progress_msg "Servicio ya iniciado"
			log_end_msg 0
		else
			/usr/sbin/$DAEMON $(id -u $USER) $(id -g $GROUP)

			if [ $? != "0" ]; then
				log_failure_msg "No se pudo iniciar el servicio"
				exit 1
			else
				log_end_msg 0
			fi
		fi
		;;

	"stop")
		log_daemon_msg "Parando servicio..."
		pid=$(ps -e | grep $DAEMON | cut -d' ' -f2)

		if [ -z "$pid" ]; then
			log_progress_msg "El servicio no estaba iniciado"
			log_end_msg 0
		else
			kill $pid

			if [ $? != 0 ]; then
				log_failure_msg "No se pudo parar el servicio"
				exit 1
			else
				log_end_msg 0
			fi
		fi
		;;

	*)
		echo "Sintaxis:" $0 "start|stop"
		exit 1
esac
